<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Modèle de données initial : tables player, word et vote.
 */
final class Version20260614145533 extends AbstractMigration
{
    public function getDescription(): string
    {
        return 'Création des tables player, word et vote (modèle de données initial)';
    }

    public function up(Schema $schema): void
    {
        $this->addSql('CREATE TABLE player (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, username VARCHAR(255) NOT NULL, token VARCHAR(255) NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_98197A655F37A13B ON player (token)');
        $this->addSql('CREATE TABLE vote (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, value VARCHAR(255) NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, player_id INT NOT NULL, word_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_5A10856499E6F5DF ON vote (player_id)');
        $this->addSql('CREATE INDEX IDX_5A108564E357438D ON vote (word_id)');
        $this->addSql('CREATE UNIQUE INDEX uniq_vote_player_word ON vote (player_id, word_id)');
        $this->addSql('CREATE TABLE word (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, value VARCHAR(255) NOT NULL, status VARCHAR(255) NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, author_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_C3F175111D775834 ON word (value)');
        $this->addSql('CREATE INDEX IDX_C3F17511F675F31B ON word (author_id)');
        $this->addSql('ALTER TABLE vote ADD CONSTRAINT FK_5A10856499E6F5DF FOREIGN KEY (player_id) REFERENCES player (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE vote ADD CONSTRAINT FK_5A108564E357438D FOREIGN KEY (word_id) REFERENCES word (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE word ADD CONSTRAINT FK_C3F17511F675F31B FOREIGN KEY (author_id) REFERENCES player (id) NOT DEFERRABLE');
    }

    public function down(Schema $schema): void
    {
        $this->addSql('ALTER TABLE vote DROP CONSTRAINT FK_5A10856499E6F5DF');
        $this->addSql('ALTER TABLE vote DROP CONSTRAINT FK_5A108564E357438D');
        $this->addSql('ALTER TABLE word DROP CONSTRAINT FK_C3F17511F675F31B');
        $this->addSql('DROP TABLE player');
        $this->addSql('DROP TABLE vote');
        $this->addSql('DROP TABLE word');
    }
}
